### ISSUE TITLE
SSM Failure on specific keys

### ISSUE THREAD

**Issue by djtecha** [luizvasconceloss/hiera-ssm-paramstore#16]
Ran into a permissions issue using the datadog module. But it looks like it might be a larger issue with the SSM lookup feature. Turns out if you run a lookup on a key that's started with '::' then it'll attempt to do a getParameters call on your top level SSM path.

$_puppetversion = lookup({ 'name' => '::puppetversion', 'default_value' => 'unknown'})

Results in:

Error: Evaluation Error: Error while evaluating a Function Call, Lookup of key '::puppetversion' failed: AWS SSM Service error User: arn:aws:sts::282708546392:assumed-role/XXXX is not authorized to perform: ssm:GetParameters on resource: arn:aws:ssm:us-east-1:XXXXX:* (file: /etc/puppetlabs/code/modules/datadog_agent/manifests/init.pp, line: 387, column: 21) on node ip-10-211-47-74.ec2.internal

I'm trying to follow best practice security so I'd rather not allow the node to walk the entire tree. Here's my current IAM

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "1",
            "Effect": "Allow",
            "Action": [
                "ssm:GetParametersByPath",
                "ssm:GetParameters",
                "ssm:GetParameter",
                "ssm:DescribeParameters"
            ],
            "Resource": [
                "arn:aws:ssm:*:*:parameter/root/stg/*",
                "arn:aws:ssm:*:*:parameter/root/stg/",
                "arn:aws:ssm:*:*:parameter/root/default*"
            ]
        }
    ]
}`

**Comment by djtecha** [comment]
Forgot to mention I'm on the 0.3.0 release running puppet 6 on amazon 2 linux

**Comment by luizvasconceloss** [comment]
I'll need more time to look into this, the problem is that `::` is converted to `/`. Would be possible to provide your hiera.yaml content?

**Comment by djtecha** [comment]
Sure 

```
version: 5

hierarchy:
  - name: "Host Data"
    path: "%{::ec2_tag_env}/%{::ec2_tag_service}/%{::fqdn}.yaml"
  - name: "Service Role Data" #Very Specific Override
    path: "%{::ec2_tag_env}/%{::ec2_tag_service}/%{::ec2_tag_type}/defaults.yaml"
  - name: "Service Data"
    path: "%{::ec2_tag_env}/%{::ec2_tag_service}/defaults.yaml"
  - name: "Environment Data"
    path: "%{::ec2_tag_env}/defaults.yaml"
  - name: "Global data"
    path: "defaults.yaml"
  - name: "AWS Parameter Store"
    lookup_key: hiera_ssm_paramstore
    uris:
      - "/root/%{::ec2_tag_env}/"
    options:
      region: us-east-1
      get_all: false
      recursive: false
```
